/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GalleryEditRouteImport } from './routes/gallery-edit'
import { Route as GalleryManageRouteImport } from './routes/gallery-manage'
import { Route as GalleryUploadRouteImport } from './routes/gallery-upload'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrganizationsRouteImport } from './routes/organizations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryEditRoute = GalleryEditRouteImport.update({
  id: '/gallery-edit',
  path: '/gallery-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryManageRoute = GalleryManageRouteImport.update({
  id: '/gallery-manage',
  path: '/gallery-manage',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryUploadRoute = GalleryUploadRouteImport.update({
  id: '/gallery-upload',
  path: '/gallery-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/calendar': typeof CalendarRoute
  '/gallery': typeof GalleryRoute
  '/gallery-edit': typeof GalleryEditRoute
  '/gallery-manage': typeof GalleryManageRoute
  '/gallery-upload': typeof GalleryUploadRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/calendar': typeof CalendarRoute
  '/gallery': typeof GalleryRoute
  '/gallery-edit': typeof GalleryEditRoute
  '/gallery-manage': typeof GalleryManageRoute
  '/gallery-upload': typeof GalleryUploadRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/calendar': typeof CalendarRoute
  '/gallery': typeof GalleryRoute
  '/gallery-edit': typeof GalleryEditRoute
  '/gallery-manage': typeof GalleryManageRoute
  '/gallery-upload': typeof GalleryUploadRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/calendar'
    | '/gallery'
    | '/gallery-edit'
    | '/gallery-manage'
    | '/gallery-upload'
    | '/login'
    | '/organizations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/calendar'
    | '/gallery'
    | '/gallery-edit'
    | '/gallery-manage'
    | '/gallery-upload'
    | '/login'
    | '/organizations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/calendar'
    | '/gallery'
    | '/gallery-edit'
    | '/gallery-manage'
    | '/gallery-upload'
    | '/login'
    | '/organizations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CalendarRoute: typeof CalendarRoute
  GalleryRoute: typeof GalleryRoute
  GalleryEditRoute: typeof GalleryEditRoute
  GalleryManageRoute: typeof GalleryManageRoute
  GalleryUploadRoute: typeof GalleryUploadRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery-edit': {
      id: '/gallery-edit'
      path: '/gallery-edit'
      fullPath: '/gallery-edit'
      preLoaderRoute: typeof GalleryEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery-manage': {
      id: '/gallery-manage'
      path: '/gallery-manage'
      fullPath: '/gallery-manage'
      preLoaderRoute: typeof GalleryManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery-upload': {
      id: '/gallery-upload'
      path: '/gallery-upload'
      fullPath: '/gallery-upload'
      preLoaderRoute: typeof GalleryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  CalendarRoute: CalendarRoute,
  GalleryRoute: GalleryRoute,
  GalleryEditRoute: GalleryEditRoute,
  GalleryManageRoute: GalleryManageRoute,
  GalleryUploadRoute: GalleryUploadRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
